controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 70  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - base_to_yaw_platform
      - yaw_to_pitch_platform

joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_to_yaw_platform
      - yaw_to_pitch_platform
    interfaces: 
      - effort
    use_local_topics: true