amcl:
  ros__parameters:
    alpha1: 3.0
    alpha2: 0.7
    alpha3: 3.5
    alpha4: 2.0
    alpha5: 0.1
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.1
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 5.0
    laser_max_range: 10.0
    laser_min_range: 0.1
    laser_model_type: "likelihood_field"
    max_beams: 810
    max_particles: 10000
    min_particles: 5000
    odom_frame_id: "odom"
    # odom_frame_id: "odometry/filtered"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.02
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: True
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 5.0
      y: 0.0
      z: 0.0
      yaw: -2.0

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True
